package Travel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author woo07008086
 */
public class ResultForm extends javax.swing.JFrame {

    /**
     * Creates new form ResultForm
     */
    public ResultForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblCover1 = new javax.swing.JLabel();
        lblCover2 = new javax.swing.JLabel();
        lblArea1 = new javax.swing.JLabel();
        lblArea2 = new javax.swing.JLabel();
        lblLength1 = new javax.swing.JLabel();
        lblLength2 = new javax.swing.JLabel();
        lblMed1 = new javax.swing.JLabel();
        lblMed2 = new javax.swing.JLabel();
        lblCruise2 = new javax.swing.JLabel();
        lblCruise1 = new javax.swing.JLabel();
        lblExcess1 = new javax.swing.JLabel();
        lblExcess2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        age1 = new javax.swing.JLabel();
        age2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total Cost : ");

        lblTotalCost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalCost.setText("0.0");

        lblTitle2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle2.setText("Costs");

        lblCover1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCover1.setText("Cover Cost");

        lblCover2.setText("0.0");

        lblArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblArea1.setText("Area Cover");

        lblArea2.setText("0.0");

        lblLength1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLength1.setText("Trip Length");

        lblLength2.setText("0.0");

        lblMed1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMed1.setText("Medical ");

        lblMed2.setText("0.0");

        lblCruise2.setText("0.0");

        lblCruise1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCruise1.setText("Cruise cover");

        lblExcess1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExcess1.setText("Excess/disc");

        lblExcess2.setText("0.0");

        name1.setText("Name");

        name2.setText("0");

        age1.setText("age:");

        age2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name2)
                        .addGap(124, 124, 124)
                        .addComponent(age1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(age2))
                    .addComponent(lblTitle2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalCost))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLength1)
                                    .addComponent(lblArea1)
                                    .addComponent(lblMed1)
                                    .addComponent(lblCruise1)
                                    .addComponent(lblExcess1)))
                            .addComponent(lblCover1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCover2)
                            .addComponent(lblArea2)
                            .addComponent(lblLength2)
                            .addComponent(lblMed2)
                            .addComponent(lblCruise2)
                            .addComponent(lblExcess2))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(name2)
                    .addComponent(age1)
                    .addComponent(age2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCover1)
                    .addComponent(lblCover2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea1)
                    .addComponent(lblArea2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLength2)
                    .addComponent(lblLength1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMed2)
                    .addComponent(lblMed1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCruise1)
                    .addComponent(lblCruise2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExcess2)
                    .addComponent(lblExcess1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalCost))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age1;
    public javax.swing.JLabel age2;
    private javax.swing.JLabel lblArea1;
    public javax.swing.JLabel lblArea2;
    private javax.swing.JLabel lblCover1;
    public javax.swing.JLabel lblCover2;
    private javax.swing.JLabel lblCruise1;
    public javax.swing.JLabel lblCruise2;
    private javax.swing.JLabel lblExcess1;
    public javax.swing.JLabel lblExcess2;
    private javax.swing.JLabel lblLength1;
    public javax.swing.JLabel lblLength2;
    private javax.swing.JLabel lblMed1;
    public javax.swing.JLabel lblMed2;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTotal;
    public javax.swing.JLabel lblTotalCost;
    private javax.swing.JLabel name1;
    public javax.swing.JLabel name2;
    // End of variables declaration//GEN-END:variables
}
